### ISSUE TITLE
Meteor.userId() missing on page refresh

### ISSUE THREAD

**Issue by EmanueleGuidotti** [dburles/two-factor-example#1]
It seems the plugin clears the `Meteor.user` on page refresh. Anyone has facing this issue before?

**Comment by dburles** [comment]
Hey @EmanueleGuidotti, just checking, do you mean refreshing after seeing the "Successfully signed in! " message?

**Comment by EmanueleGuidotti** [comment]
Hi @dburles sorry for opening this issue. It was my fault. I added two lines in the example code which had broken the whole flow.
`      Accounts._unstoreLoginToken();
      Accounts._autoLoginEnabled = false;
`

Removing those lines has solved the problem.
I'm really sorry for that.
